application: mara-places
version: 1
runtime: go
api_version: go1

handlers:
- url: /place
  script: _go_app
- url: /maraplace
  script: _go_app
- url: /
  static_files: index.html
  upload: index.html
