application: world-love
version: 1
runtime: go
api_version: go1

handlers:
- url: /worldlove
  script: _go_app
- url: /
  static_files: index.html
  upload: index.html
- url: /static
  static_dir: static
